"""empty message

Revision ID: 052e160bdd61
Revises: 
Create Date: 2024-04-30 10:45:17.858654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052e160bdd61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'credential_offer', ['id'])
    op.create_unique_constraint(None, 'credential_revocation_status_list', ['id'])
    op.create_unique_constraint(None, 'data_agreement', ['id'])
    op.add_column('issue_credential_record', sa.Column('limitedDisclosure', sa.Boolean(), server_default='True', nullable=False))
    op.create_unique_constraint(None, 'issue_credential_record', ['id'])
    op.create_unique_constraint(None, 'organisation', ['id'])
    op.create_unique_constraint(None, 'v2_data_agreement', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'v2_data_agreement', type_='unique')
    op.drop_constraint(None, 'organisation', type_='unique')
    op.drop_constraint(None, 'issue_credential_record', type_='unique')
    op.drop_column('issue_credential_record', 'limitedDisclosure')
    op.drop_constraint(None, 'data_agreement', type_='unique')
    op.drop_constraint(None, 'credential_revocation_status_list', type_='unique')
    op.drop_constraint(None, 'credential_offer', type_='unique')
    # ### end Alembic commands ###
