"""empty message

Revision ID: 3be60cbb77ee
Revises: f2622afe5eae
Create Date: 2024-05-01 00:34:20.174467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be60cbb77ee'
down_revision: Union[str, None] = 'f2622afe5eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_record', sa.Column('verified', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'verification_record', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_record', type_='unique')
    op.drop_column('verification_record', 'verified')
    # ### end Alembic commands ###
