"""empty message

Revision ID: 4b55f8ee9ea5
Revises: 052e160bdd61
Create Date: 2024-04-30 16:49:03.453431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b55f8ee9ea5'
down_revision: Union[str, None] = '052e160bdd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_credential_record', sa.Column('credential', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('issue_credential_record', sa.Column('disclosureMapping', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('issue_credential_record', 'dataAgreementId',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issue_credential_record', 'dataAgreementId',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('issue_credential_record', 'disclosureMapping')
    op.drop_column('issue_credential_record', 'credential')
    # ### end Alembic commands ###
