"""empty message

Revision ID: f2622afe5eae
Revises: 792325ac96d1
Create Date: 2024-05-01 00:31:33.929153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2622afe5eae'
down_revision: Union[str, None] = '792325ac96d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisationId', sa.UUID(), nullable=False),
    sa.Column('vp_token_request_state', sa.String(), nullable=True),
    sa.Column('vp_token_request', sa.String(), nullable=True),
    sa.Column('vp_token_qr_code', sa.String(), nullable=True),
    sa.Column('vp_token_response', sa.String(), nullable=True),
    sa.Column('presentationSubmission', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisationId'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_record')
    # ### end Alembic commands ###
